# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: trailing-whitespace
        types: [python]
    -   id: end-of-file-fixer
        types: [python]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        name: flake8-blocking
        args: [ '--isolated', '--select=P,F401,F821,F901', '--ignore=P101,P102' ]
        additional_dependencies:
            - flake8-string-format
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
- repo: local
  # Eat your own dog food
  # Although redundant with regular flake8 present above
  # We run our hook against the diff
  hooks:
    - id: flake8-staged-diff
      name: flake8-staged-diff
      language: python
      entry: flake8-staged-diff
      args: [ '--isolated', '--select=P,F401,F821,F901', '--ignore=P101,P102' ]
      additional_dependencies:
        - flake8-string-format
      pass_filenames: true