name: flake8-staged-diff
on:
  # All PR
  pull_request:
  # master branch merge
  push:
    branches:
      - master
  # release tags
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'

jobs:
  linting:
    # Run pre-commit (https://pre-commit.com/)
    # which runs pre-configured linter & autoformatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: bash .github/workflows/install_ci_python_dep.sh
    - run: pre-commit run -a

  test:
    # Test suite run against recent python versions
    # and against a few combination of MongoDB and pymongo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11, pypy3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install ci dependencies
      run: |
        bash .github/workflows/install_ci_python_dep.sh
    - name: install dep
      run: pip install .
    - name: Run test suite
      run: pytest

  build-n-publish:
    runs-on: ubuntu-latest
    needs: [linting, test]
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: build wheel
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: publish pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_token }}